### ISSUE TITLE
Clean up branches of this repo

### ISSUE THREAD

**Issue by DanielePucci** [ami-iit/robots-configuration#43] opened 2023-10-13 15:18 UTC
As discussed in during https://github.com/ami-iit/lab-organisation/issues/458 (discussion point 5), we should reduce the number of branches in this repo. We decided that
* @gabrielenava reviews and closes/merges the iCub3/iRonCub3 branches 
* @lrapetti @GiulioRomualdi @mebbaid @S-Dafarra @CarlottaSartore  review and close/merge the ergoCub branches

**Comment by traversaro** [comment] 2023-10-13 15:22
If someone really needs a branch for archive purpose, he/she can push the branch to their personal fork.

**Comment by gabrielenava** [comment] 2024-01-25 11:29
Hello @isorrentino @GiulioRomualdi @CarlottaSartore @mebbaid @HosameldinMohamed I have created a table to collect all branches that have not been active in the last months. I also pointed to you because you were the last persons who committed in those branches. Can you indicate if these branches can be deleted or not?

| Branch Name | Last person who committed |Can the branch be deleted? YES/NO |
|:--------------------:|:----------------------------------------:|:---------------------------------------:|
|[to_delete/balancing_half_foot](https://github.com/ami-iit/robots-configuration/tree/to_delete/balancing_half_foot)|@isorrentino|   YES|
|[13Nov2023](https://github.com/ami-iit/robots-configuration/tree/13Nov2023)| @isorrentino|  YES   |
|[iit_20y](https://github.com/ami-iit/robots-configuration/tree/iit_20y)| @isorrentino |   YES  |
|[wbd](https://github.com/ami-iit/robots-configuration/tree/wbd)| @GiulioRomualdi | YES    |
|[testVelocityThres](https://github.com/ami-iit/robots-configuration/tree/testVelocityThres)|@isorrentino|   YES     |
[ergocubsn000_rde_interface](https://github.com/ami-iit/robots-configuration/tree/ergocubsn000_rde_interface)| @isorrentino|  NO |   
|[test_left_leg_rde](https://github.com/ami-iit/robots-configuration/tree/test_left_leg_rde)|@isorrentino|     YES      |
| [fix_ft_firmware_version](https://github.com/ami-iit/robots-configuration/tree/fix_ft_firmware_version) | @CarlottaSartore  |   YES    |
| [remove_torso_pitch_ergocubSN00](https://github.com/ami-iit/robots-configuration/tree/remove_torso_pitch_ergocubSN00) | @CarlottaSartore  |  YES      |
| [ergoCubSN000_torso_and_arms](https://github.com/ami-iit/robots-configuration/tree/ergoCubSN000_torso_and_arms) | @GiulioRomualdi  |    YES   |
| [ironcub_ergocub_walking](https://github.com/ami-iit/robots-configuration/tree/ironcub_ergocub_walking) | @CarlottaSartore  |    YES   |
| [no_r_forearm](https://github.com/ami-iit/robots-configuration/tree/no_r_forearm)  | @mebbaid  |     YES  |
| [devel_ergoCubSN000_torque_control](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000_torque_control)  | @isorrentino (Lorenzo left, pointing to you because it is torque control) |  YES     |
| [devel_ergoCubSN000](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000) | @GiulioRomualdi  |   YES    |
|[devel_ergoCubSN000_1kHz](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000_1kHz)  | @GiulioRomualdi  |     YES  |
| [devel_ergoCubSN000_without_right_wrist](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000_without_right_wrist)  | @GiulioRomualdi  |   YES    |
| [add_ft_non_linear_calib](https://github.com/ami-iit/robots-configuration/tree/add_ft_non_linear_calib) | @isorrentino  |  YES     |
| [devel_iCubGenova09_skin_manager](https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova09_skin_manager) | @GiulioRomualdi  |    YES   |
| [friction_compensation](https://github.com/ami-iit/robots-configuration/tree/friction_compensation) | @isorrentino  |   YES    |
| [icubgenova09/torque_control_gains](https://github.com/ami-iit/robots-configuration/tree/icubgenova09/torque_control_gains)  | @isorrentino (Lorenzo left, pointing to you because it is torque control)  |   YES    |
| [devel_iCubGenova09_1kHz](https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova09_1kHz)  | @GiulioRomualdi  |   YES    |
| [ft_secondary_calibration](https://github.com/ami-iit/robots-configuration/tree/ft_secondary_calibration) | @isorrentino  |   YES    |
|[testWBDKF](https://github.com/ami-iit/robots-configuration/tree/testWBDKF)  | @isorrentino   |    YES   |
| [exposeHeadOrientation](https://github.com/ami-iit/robots-configuration/tree/exposeHeadOrientation) | @isorrentino  |   YES    |
| [icub02-prefix](https://github.com/ami-iit/robots-configuration/tree/icub02-prefix)  |  This is iCubGenova02, not sure if we should ask someone or just delete this branch|    YES   |
| [testTemperatureOffset](https://github.com/ami-iit/robots-configuration/tree/testTemperatureOffset) | @HosameldinMohamed this was done by Francisco, pointing to you beacuse FT temperature |  YES  |


cc @ami-iit/artificial-mechanical-intelligence if in one of these branches there is some code that is important to you, please comment or save it in a fork as suggested in https://github.com/ami-iit/robots-configuration/issues/43#issuecomment-1761698565

**Comment by S-Dafarra** [comment] 2024-01-25 11:42
> [icub02-prefix](https://github.com/ami-iit/robots-configuration/tree/icub02-prefix)	This is iCubGenova02, not sure if we should ask someone or just delete this branch

This was to run the robot-robot collaboration experiments. It changed the prexes of the ports from ``icub`` to ``icub02``

**Comment by lrapetti** [comment] 2024-01-25 18:14
> > [icub02-prefix](https://github.com/ami-iit/robots-configuration/tree/icub02-prefix)	This is iCubGenova02, not sure if we should ask someone or just delete this branch
> 
> This was to run the robot-robot collaboration experiments. It changed the prexes of the ports from `icub` to `icub02`

I confirm. I think you can delete it, and eventually ro reproduce the configuration the procedure is documented [here](https://icub-tech-iit.github.io/documentation/icub_setup_multiple_robots/two_robots_real/#how-to-use-two-real-icub-robots-on-the-same-network).

Concerning the other two branches I was the last one committing, they contain gains for specific experiments, feel free to delete :wink:.

**Comment by gabrielenava** [comment] 2024-01-26 17:00
thank you @lrapetti!

**Comment by isorrentino** [comment] 2024-01-26 17:49
@gabrielenava I updated the comment [here](https://github.com/ami-iit/robots-configuration/issues/43#issuecomment-1909972217).

**Comment by gabrielenava** [comment] 2024-01-29 14:42
thank you @isorrentino! I deleted the branches you confirmed it was possible to delete!

**Comment by HosameldinMohamed** [comment] 2024-01-29 15:28
> @HosameldinMohamed this was done by Francisco, pointing to you beacuse FT temperature

For me, we can delete it. The branch has only one commit ahead of the base branch and adds a few lines. The most important ones are some coefficients for the calibration matrix and offset values for the leg fts:

```xml
          <param name="l_leg_ft_sensor"> (7.131399e-01,3.590998e-02,-4.660118e-02,2.106746e-01,8.257131e-01,1.747785e-01
                                            ,1.376450e-02,3.644623e-01,9.866621e-03,-1.563210e+00,-5.692031e-02,1.550167e+00
                                            ,-9.536545e-02,2.201782e-01,9.891589e-01,1.739220e+00,3.757220e-01,2.579337e-01
                                            ,-6.477639e-03,-2.979106e-02,2.786408e-03,7.337876e-01,2.200818e-02,-8.247335e-02
                                            ,1.010060e-02,2.463272e-03,-2.191996e-03,1.592894e-02,8.895674e-01,-4.525067e-02
                                            ,2.165058e-03,1.711693e-03,-4.406373e-05,-8.685050e-03,-1.765709e-02,9.057390e-01)</param>

            <param name="r_leg_ft_sensor">
                    (9.308601e-01,7.328130e-03,-1.211788e-02,-1.123839e-01,-2.977943e-01,-1.954805e-02
                    ,-8.177519e-02,7.160387e-01,-4.158542e-02,1.077732e+00,4.997348e-01,2.431916e+00
                    ,-4.174433e-02,-1.784640e-01,9.661752e-01,-1.386611e+00,1.538259e-01,-5.603641e-01
                    ,-1.877732e-03,-3.220898e-03,-6.874089e-04,9.546012e-01,1.329514e-02,2.982738e-02
                    ,-2.466464e-03,2.580501e-03,-3.510048e-04,6.640786e-03,9.513549e-01,4.179682e-02
		                ,2.002912e-03,3.654545e-04,3.323602e-04,-1.106579e-02,-8.070312e-03,9.706656e-01)
	         </param>

        </group>

        <group name="FT_TEMPERATURE_COEFFICIENTS">
              <param name="l_leg_ft_sensor">(-0.0933  ,  0.2048  ,  1.3342  , -0.0155  ,  0.0027  ,  0.0039  , 30.4064)</param>
        </group>

        <group name="FT_OFFSET">
              <param name="l_leg_ft_sensor">(24.8009  , -6.2369 , -62.0044 , -0.0588 ,  -0.2425  ,  0.1253)</param>
             <!-- <param name="r_leg_ft_sensor">(0.0,0.0,0.0,0.0,0.0,0.0)</param> -->
       </group>
```

But I don't think they are valid anymore since they were obtained 4 years ago!

**Comment by gabrielenava** [comment] 2024-01-29 15:29
thanks @HosameldinMohamed! deleting it!

**Comment by CarlottaSartore** [comment] 2024-02-05 14:16
@gabrielenava  you can delete my branches, they were mainly for the tests performed with @lrapetti  where we needed to remove the pitch. 

We also made some changes in the port prefix of whole body dynamics for having two robots walking together 

` <param name="portPrefix">/ironcub/wholebodydynamics</param>`
 
 but we have an issue that collects all the changes needed if we want to replicate the experiments.
 
I  updated the comment accordingly

**Comment by gabrielenava** [comment] 2024-02-05 17:14
thanks @CarlottaSartore, branches deleted!

**Comment by mebbaid** [comment] 2024-03-01 10:42
The [no_r_forearm](https://github.com/ami-iit/robots-configuration/tree/no_r_forearm)  branch with this commit https://github.com/ami-iit/robots-configuration/commit/a0e923e399d127607917dc36a882d3487c560a1b is not needed anymore and we can delete it. I also updated the table.

**Comment by GiulioRomualdi** [comment] 2024-03-01 10:58
- [devel_ergoCubSN000](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000) can be deleted
- [wbd](https://github.com/ami-iit/robots-configuration/tree/wbd) you can delete it
- [ergoCubSN000_torso_and_arms](https://github.com/ami-iit/robots-configuration/tree/ergoCubSN000_torso_and_arms) you can delete it
- [devel_iCubGenova09_skin_manager](https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova09_skin_manager) you can delete I copied it to my fork
- [devel_iCubGenova09_1kHz](https://github.com/ami-iit/robots-configuration/tree/devel_iCubGenova09_1kHz) you can deleted
- [devel_ergoCubSN000_1kHz](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000_1kHz) You can delete, I copied it to my fork
- [devel_ergoCubSN000_without_right_wrist](https://github.com/ami-iit/robots-configuration/tree/devel_ergoCubSN000_without_right_wrist) delete

**Comment by gabrielenava** [comment] 2024-03-01 16:04
thank you @GiulioRomualdi and @mebbaid!

Now the repo has only 7 branches, and all of them have been marked as useful! Closing the issue, the task is completed

**Closed as completed by gabrielenava** 2024-03-01 16:04 UTC
